### PR TITLE
Framework update to SMAPI 2.7

### PR DESCRIPTION
**Pull request by Slamerz**

### CODE REVIEW

**Comment by Slamerz** [comment]
Custom Update and Bush reset not updated.

**Comment by Slamerz** [comment]
Tonight a friend and I found that if you're in multiplayer and not the host there is an error occurring that we've traced to the game update tick in the framework, still investigating to to get a better idea of what's going on for a potential fix

**Comment by Entoarox** [comment]
Work is taking to much time, and apparently trying to sync things broke everything on my end, so I'll need time to actually fix that, which, annoyingly, I dont really have.

So, Hereby, I Entoarox, give Slamerz, uniform permission to update and maintain my mods for the stardew valley 1.3 update.

Good luck! 👍

**Comment by Pathoschild** [comment]
Thanks! Merged into `develop` for the next update. There are a few changes I want to make (e.g. fixing `bush_reset`), but I'll do those after merging your pull requests.

**Pull request merged**
